Add Import/Export
PathDNA/turtleDB pull request #4
Opened 2017-08-10 18:18 UTC by itsmontoya

2017-08-10 18:37 UTC, shahzilabid commented on slave.go
> +	if imp == nil {
Really like the idea of a generic importer. Great stuff

2017-08-10 18:37 UTC, shahzilabid commented on importers/http.go
> +func NewHTTPImporter(loc string) (hp *HTTPImporter, err error) {
Hmm I can't see where you define this HTTPImporter struct?

2017-08-10 18:48 UTC, OneOfOne requested changes
great stuff man, just Shahzil's notes + 2 little notes

2017-08-10 18:48 UTC, OneOfOne commented on importers/http.go
> +func (h *HTTP) SetJar(jar http.CookieJar) {
Why use cookies instead of an api key we can pass as a header or query param?

2017-08-10 18:48 UTC, OneOfOne commented on importers/http.go
> +	io.Copy(buf, resp.Body)
&buf, i don't think this compiled right now

2017-08-10 19:01 UTC, itsmontoya commented on importers/http.go
> +func (h *HTTP) SetJar(jar http.CookieJar) {
Cookies seems very universal for all systems. I can totally add a header option though too!

2017-08-10 22:22 UTC, shahzilabid commented
Shahzils-MacBook-Pro:turtleDB shahzilabid$ go build
# github.com/itsmontoya/mrT
../../itsmontoya/mrT/mrT.go:233: m.mw.List undefined (type *middleware.MWs has no field or method List)

I'm on branch add_for_each_raw for mrT

2017-08-10 22:24 UTC, itsmontoya commented
@shahzilabid can you try git pull on itsmontoya/middleware?

2017-08-10 22:28 UTC, shahzilabid commented
Worked. New error: types/bytes/turtle.go:120: not enough arguments in call to t.mrT.ForEach

2017-08-11 17:10 UTC, itsmontoya commented
![](https://github.trello.services/images/mini-trello-icon.png) [TurtleDB copyTo feature](https://trello.com/c/ixFl50z4/205-turtledb-copyto-feature)

2017-08-11 17:10 UTC, itsmontoya commented
![](https://github.trello.services/images/mini-trello-icon.png) [TurtleDB copyTo feature](https://trello.com/c/ixFl50z4/205-turtledb-copyto-feature)

2017-08-11 18:00 UTC, shahzilabid approved these changes
Great job man! Really clean. Will get started on the client changes today. Will come back to you with any questions

2017-08-11 20:08 UTC, OneOfOne approved these changes

2017-08-11 20:08 UTC, merged